export const FETCH_DATA_TO_LIST = 'FETCH_DATA_TO_LIST'
export const FETCH_USERS_LIST = 'FETCH_USERS_LIST'
export const FETCH_USER_DATA = 'FETCH_USERS_LIST'
export const FETCH_MARK_LIST = 'FETCH_MARK_LIST'


export const ADD_COLUMN = 'ADD_COLUMN'
export const ADD_TASK_TO_COLUMN = 'ADD_TASK_TO_COLUMN'
export const TASK_POPUP_ACTIVATION = 'TASK_POPUP_ACTIVATION'
export const TASK_POPUP_DATA_ADD = 'TASK_POPUP_DATA_ADD'
// export const TASK_POPUP_DATA_EDIT = 'TASK_POPUP_DATA_EDIT'
export const TASK_POPUP_COMMENT_ADD = 'TASK_POPUP_COMMENT_ADD'
export const TASK_POPUP_DATE_CHANGE = 'TASK_POPUP_DATE_CHANGE'

export const SHOW_PART_ADD_FORM = 'SHOW_PART_ADD_FORM'
export const ADD_PARTICIPANT_TO_TASK = 'ADD_PARTICIPANT_TO_TASK'
export const ADD_PART_TO_POPUP = 'ADD_PART_TO_POPUP'
export const SHOW_MARK_ADD_FORM = 'SHOW_MARK_ADD_FORM'
export const SHOW_DATE_FORM = 'SHOW_DATE_FORM'
export const ADD_MARK_TO_TASK = 'ADD_MARK_TO_TASK'
export const SET_DATE_TO_TASK = 'SET_DATE_TO_TASK'

export const CHANGE_TASK_DATE = 'CHANGE_TASK_DATE'
export const CHANGE_MONTH = 'CHANGE_MONTH'


export const SET_CART = 'SET_CART'
export const RESET_CART = 'RESET_CART'



export const CHANGE_TASK_POSITION = 'CHANGE_TASK_POSITION'


//AuthActions
export const LOGIN_USER = 'LOGIN_USER'
export const REFRESH_TOKEN = 'REFRESH_TOKEN'
